# Generated by Django 3.2 on 2022-06-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0003_parent_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.school'),
        ),
    ]
