# Generated by Django 3.2 on 2022-06-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0005_auto_20220626_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.school'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.school'),
        ),
    ]
